# Generated by Django 3.1.3 on 2021-07-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20210711_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinevi',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uielement',
            name='user',
        ),
        migrations.AddField(
            model_name='machinevi',
            name='mac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='machine.machineuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uielement',
            name='mac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='machine.machineuser'),
            preserve_default=False,
        ),
    ]
