# Generated by Django 3.1.3 on 2021-07-16 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20210716_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='uiElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField()),
                ('coolant', models.IntegerField()),
                ('oilTemp', models.IntegerField()),
                ('voltage', models.FloatField()),
                ('fuel', models.FloatField()),
                ('oilPress', models.FloatField()),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machineuser')),
            ],
        ),
        migrations.CreateModel(
            name='machineVI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('time_at', models.TimeField(auto_now_add=True)),
                ('rh', models.FloatField()),
                ('sh', models.FloatField()),
                ('vr', models.FloatField()),
                ('vy', models.FloatField()),
                ('vb', models.FloatField()),
                ('vry', models.FloatField()),
                ('vyb', models.FloatField()),
                ('vbr', models.FloatField()),
                ('dgr', models.FloatField()),
                ('dgy', models.FloatField()),
                ('dgb', models.FloatField()),
                ('dgry', models.FloatField()),
                ('dgyb', models.FloatField()),
                ('dgbr', models.FloatField()),
                ('ir', models.FloatField()),
                ('iy', models.FloatField()),
                ('ib', models.FloatField()),
                ('pf', models.FloatField()),
                ('powr', models.FloatField()),
                ('powy', models.FloatField()),
                ('powb', models.FloatField()),
                ('apc', models.FloatField()),
                ('apr', models.FloatField()),
                ('apy', models.FloatField()),
                ('apb', models.FloatField()),
                ('kwh', models.FloatField()),
                ('trhr', models.FloatField()),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machineuser')),
            ],
        ),
    ]
