# Generated by Django 4.0.6 on 2022-09-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_machinevi_uielement'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineuser',
            name='machine_kv',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machineuser',
            name='machine_phase',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
